package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T11:04:18.754-05:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "FacadeProducto",
                  wsdlLocation = "file:/home/juan.garcia/workspace/B2C-Productos/src/main/resources/ServiceProducto.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class FacadeProducto extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "FacadeProducto");
    public final static QName BasicHttpBindingIb2C = new QName("http://tempuri.org/", "BasicHttpBinding_Ib2c");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/juan.garcia/workspace/B2C-Productos/src/main/resources/ServiceProducto.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FacadeProducto.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/juan.garcia/workspace/B2C-Productos/src/main/resources/ServiceProducto.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FacadeProducto(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FacadeProducto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacadeProducto() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FacadeProducto(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FacadeProducto(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FacadeProducto(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Ib2C
     */
    @WebEndpoint(name = "BasicHttpBinding_Ib2c")
    public Ib2C getBasicHttpBindingIb2C() {
        return super.getPort(BasicHttpBindingIb2C, Ib2C.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ib2C
     */
    @WebEndpoint(name = "BasicHttpBinding_Ib2c")
    public Ib2C getBasicHttpBindingIb2C(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIb2C, Ib2C.class, features);
    }

}
