package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T11:04:18.720-05:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Ib2c")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.ObjectFactory.class})
public interface Ib2C {

    @WebMethod(action = "http://tempuri.org/Ib2c/crearProducto")
    @Action(input = "http://tempuri.org/Ib2c/crearProducto", output = "http://tempuri.org/Ib2c/crearProductoResponse")
    @RequestWrapper(localName = "crearProducto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CrearProducto")
    @ResponseWrapper(localName = "crearProductoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CrearProductoResponse")
    @WebResult(name = "crearProductoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ProductoResultado crearProducto(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.Productos value
    );

    @WebMethod(action = "http://tempuri.org/Ib2c/eliminarProducto")
    @Action(input = "http://tempuri.org/Ib2c/eliminarProducto", output = "http://tempuri.org/Ib2c/eliminarProductoResponse")
    @RequestWrapper(localName = "eliminarProducto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarProducto")
    @ResponseWrapper(localName = "eliminarProductoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarProductoResponse")
    @WebResult(name = "eliminarProductoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ProductoResultado eliminarProducto(
        @WebParam(name = "ObjProResultado", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ProductoMI objProResultado
    );

    @WebMethod(action = "http://tempuri.org/Ib2c/rankingProducto")
    @Action(input = "http://tempuri.org/Ib2c/rankingProducto", output = "http://tempuri.org/Ib2c/rankingProductoResponse")
    @RequestWrapper(localName = "rankingProducto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RankingProducto")
    @ResponseWrapper(localName = "rankingProductoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RankingProductoResponse")
    @WebResult(name = "rankingProductoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.Productos rankingProducto(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.Productos value
    );

    @WebMethod(action = "http://tempuri.org/Ib2c/listarProductoDescripcion")
    @Action(input = "http://tempuri.org/Ib2c/listarProductoDescripcion", output = "http://tempuri.org/Ib2c/listarProductoDescripcionResponse")
    @RequestWrapper(localName = "listarProductoDescripcion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarProductoDescripcion")
    @ResponseWrapper(localName = "listarProductoDescripcionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarProductoDescripcionResponse")
    @WebResult(name = "listarProductoDescripcionResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.Productos listarProductoDescripcion(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.Productos value
    );

    @WebMethod(action = "http://tempuri.org/Ib2c/listarProductoCodigo")
    @Action(input = "http://tempuri.org/Ib2c/listarProductoCodigo", output = "http://tempuri.org/Ib2c/listarProductoCodigoResponse")
    @RequestWrapper(localName = "listarProductoCodigo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarProductoCodigo")
    @ResponseWrapper(localName = "listarProductoCodigoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarProductoCodigoResponse")
    @WebResult(name = "listarProductoCodigoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ProductoResultado listarProductoCodigo(
        @WebParam(name = "ObjProResultado", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ProductoMI objProResultado
    );

    @WebMethod(action = "http://tempuri.org/Ib2c/modificarProducto")
    @Action(input = "http://tempuri.org/Ib2c/modificarProducto", output = "http://tempuri.org/Ib2c/modificarProductoResponse")
    @RequestWrapper(localName = "modificarProducto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarProducto")
    @ResponseWrapper(localName = "modificarProductoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarProductoResponse")
    @WebResult(name = "modificarProductoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ProductoResultado modificarProducto(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.Productos value
    );

    @WebMethod(action = "http://tempuri.org/Ib2c/listarProductoNombre")
    @Action(input = "http://tempuri.org/Ib2c/listarProductoNombre", output = "http://tempuri.org/Ib2c/listarProductoNombreResponse")
    @RequestWrapper(localName = "listarProductoNombre", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarProductoNombre")
    @ResponseWrapper(localName = "listarProductoNombreResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarProductoNombreResponse")
    @WebResult(name = "listarProductoNombreResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ProductoResultado listarProductoNombre(
        @WebParam(name = "ObjProResultado", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ProductoFiltro objProResultado
    );
}
